apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-eegd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-eegd
    app.kubernetes.io/part-of: build-suite-test-application-zkgi
  name: build-suite-test-component-git-source-eegd
  namespace: build-e2e-aed2fdb9-188d-4b9b-947e-cc412fa56fd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-component-git-source-eegd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-component-git-source-eegd
    spec:
      containers:
      - image: quay.io/psturc/test-images:2b6ef178e1944532a6e9e019e79c6374
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
