apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-eegd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-eegd
    app.kubernetes.io/part-of: build-suite-test-application-zkgi
  name: build-suite-test-component-git-source-eegd
  namespace: build-e2e-aed2fdb9-188d-4b9b-947e-cc412fa56fd2
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-git-source-eegd
status:
  loadBalancer: {}
